### ISSUE TITLE
编译GalaxyEngine时报错

### ISSUE THREAD

**Issue by turbokernel** [ApsaraDB/galaxysql#11]
系统为Debian 10
g++ (Debian 7.4.0-6) 7.4.0
gcc (Debian 7.4.0-6) 7.4.0

报错信息为：
In file included from /root/ApsaraDB/galaxyengine/sql/sys_vars.cc:44:0:
/root/ApsaraDB/galaxyengine/sql/sys_vars.cc:6785:66: error: ‘FALSE’ was not declared in this scope
     SESSION_ONLY(sequence_read_skip_cache), NO_CMD_LINE, DEFAULT(FALSE),
                                                                  ^
/root/ApsaraDB/galaxyengine/sql/sys_vars.h:102:20: note: in definition of macro ‘DEFAULT’
 #define DEFAULT(X) X
                    ^
/root/ApsaraDB/galaxyengine/sql/sys_vars.cc:6785:66: note: suggested alternative: ‘FILE’
     SESSION_ONLY(sequence_read_skip_cache), NO_CMD_LINE, DEFAULT(FALSE),
                                                                  ^
/root/ApsaraDB/galaxyengine/sql/sys_vars.h:102:20: note: in definition of macro ‘DEFAULT’
 #define DEFAULT(X) X
                    ^
/root/ApsaraDB/galaxyengine/sql/sys_vars_ext.cc:263:48: error: ‘FALSE’ was not declared in this scope
                                        DEFAULT(FALSE), NO_MUTEX_GUARD,
                                                ^
/root/ApsaraDB/galaxyengine/sql/sys_vars.h:102:20: note: in definition of macro ‘DEFAULT’
 #define DEFAULT(X) X
                    ^
/root/ApsaraDB/galaxyengine/sql/sys_vars_ext.cc:263:48: note: suggested alternative: ‘FILE’
                                        DEFAULT(FALSE), NO_MUTEX_GUARD,
                                                ^
/root/ApsaraDB/galaxyengine/sql/sys_vars.h:102:20: note: in definition of macro ‘DEFAULT’
 #define DEFAULT(X) X
                    ^
make[2]: *** [sql/CMakeFiles/sql_main.dir/build.make:3055: sql/CMakeFiles/sql_main.dir/sys_vars.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:11487: sql/CMakeFiles/sql_main.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

**Comment by songleiwang** [comment]
It will be fixed in galaxyengine, please reopen it in galaxyengine.
