### ISSUE TITLE
where is x-paxos

### ISSUE THREAD

**Issue by Zeratulllll** [ApsaraDB/galaxysql#14]

**Comment by shgxwxl** [comment]
1

**Comment by arkbriar** [comment]
It is an essential feature to enable disaster tolerance. Can't wait for that!

**Comment by kenryhuang** [comment]
we are working on it. it's 1st priority task of whole project.

**Comment by realXuJiang** [comment]
+1

**Comment by agapple** [comment]
[[XPaxos] support xpaxos protocol](https://github.com/ApsaraDB/galaxyengine/commit/074bc5edebcbc68602ee8fb391ac7a9b168d6fab)
