### ISSUE TITLE
why is the repo name galaxysql, not polardb-x

### ISSUE THREAD

**Issue by hiddenbomb** [ApsaraDB/galaxysql#3]

**Comment by UnderTreeTech** [comment]
+1

**Comment by jangels** [comment]
盖乐世

**Comment by hiddenbomb** [comment]
@Oldbread3
Other databases such as TiDB, OceanBase, have the same brand name both in open source and inner source/commercial versions. I think this may be a good action to enhance the public awareness and recognition of the database.

I doubt people may be confused between Galaxy series and PolarDB? Especially when PolarDB brand has been well-known among many developers.
