### ISSUE TITLE
welcome to native compatible openanolis https://openanolis.cn/

### ISSUE THREAD

**Issue by vitan** [ApsaraDB/galaxysql#30]
https://openanolis.cn/ 
龙蜥操作系统(Anolis OS)  版本秉承与国际主流Linux厂商发行版 100% 兼容的原则，且提供配套的迁移工具，助力用户完美平滑地迁移至龙蜥操作系统(Anolis OS)，满足CentOS停服后的各领域、各行业用户的使用习惯和需求。在硬件生态方面通过和Intel 及国内芯片厂商的合作，支持Intel、海光、兆芯、飞腾、鲲鹏等一系列芯片平台，进行软、硬一体的优化，充分发挥硬件平台的性能。

**Comment by hustfxj** [comment]
It looks nice !!
