### ISSUE TITLE
com.alibaba.polardbx.server.ServerConnection#ServerConnection

### ISSUE THREAD

**Issue by wanhuhou** [ApsaraDB/galaxysql#32]
重复代码

        instanceId = CobarServer.getInstance().getConfig().getSystem().getInstanceId();

        instanceId = CobarServer.getInstance().getConfig().getSystem().getInstanceId();

**Comment by pyson** [comment]
Thanks for your code review. This duplicated code will be optimized later. And it is recommend that you can take part in our development and summit a merge request to optimize the code here~
