### ISSUE TITLE
[bug] A security vulnerability for log4j < 2.15

### ISSUE THREAD

**Issue by seekelvis** [ApsaraDB/galaxysql#40]
There is a security vulnerability for log4j < 2.15. The log4j version should be updated to latest.

Does the bug affect the image galaxysql, galaxyengine and galaxycdc? 

Look forward to your reply~

**Comment by hustfxj** [comment]
Thank you for @seekelvis , the bug don't affect the galaxy.

**Comment by seekelvis** [comment]
Thanks for your reply
