### ISSUE TITLE
【PXC-9001】CN启动失败, 报错: “No found any leader for metadb storage”

### ISSUE THREAD

**Issue by Cleverdada** [ApsaraDB/galaxysql#44]
操作路径：
源码编译DN启动后
1 初始化 执行能够正常完成 bin/startup.sh -I -P asdf1234ghjk5678 -r "admin" -d 127.0.0.1:4886:32886 -u polardbx_root -S "123456"
2 把 metaDbPasswd=BVUB3NoOBdCXPv+X2Wa3es6Ng1tzChSd9Vzdm2RVaBo= 放到 conf/server.properties
3 启动 命令没有报错  bin/startup.sh -P asdf1234ghjk5678  
4 连接数据库报错了，8527端口没有监听    mysql -h127.0.0.1 -P8527 -upolardbx_root -p123456
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)

配置如下：
![image](https://user-images.githubusercontent.com/11186845/156718592-9b113776-ebf2-4f6c-b69a-e6e65f655c15.png)

报错日志：
![image](https://user-images.githubusercontent.com/11186845/156718484-27920fb9-29b6-4e9d-85b0-c95171401db8.png)

**Comment by Cleverdada** [comment]
需要尝试复现，可能要久等一下

**Comment by fyzjhh** [comment]
> 需要尝试复现，可能要久等一下

这个问题最初出现的错误是在 初始化的时候 ， 上面提到的异常信息 ，是在附加其他操作才产生的。 

`
bin/startup.sh \
    -I \
    -P asdf1234ghjk5678 \
    -d 127.0.0.1:4886:32886 \
    -r "" \
    -u polardbx_root \
    -S "123456"

Exception in thread "main" ERR-CODE: [PXC-10004][ERR_X_PROTOCOL_RESULT] Fatal error when fetch data: Unable to switch context to user root HY000 
	at com.alibaba.polardbx.rpc.result.XResult.internalFetchOneObject(XResult.java:926)
	at com.alibaba.polardbx.rpc.result.XResult.waitFinish(XResult.java:508)
	at com.alibaba.polardbx.rpc.result.XResult.internalFetchOneObject(XResult.java:567)
	at com.alibaba.polardbx.rpc.result.XResult.waitFinish(XResult.java:508)
	at com.alibaba.polardbx.rpc.result.XResult.internalFetchOneObject(XResult.java:567)
	at com.alibaba.polardbx.rpc.result.XResult.internalFetchOneObject(XResult.java:551)
	at com.alibaba.polardbx.rpc.result.XResult.finishBlockMode(XResult.java:159)
	at com.alibaba.polardbx.rpc.client.XSession.execUpdate(XSession.java:1703)
	at com.alibaba.polardbx.rpc.pool.XConnection.execUpdate(XConnection.java:281)
	at com.alibaba.polardbx.rpc.compatible.XStatement.executeUpdateX(XStatement.java:55)
	at com.alibaba.polardbx.rpc.compatible.XStatement.executeUpdate(XStatement.java:82)
	at com.alibaba.polardbx.gms.metadb.MetaDbDataSource.initTsoServicesX(MetaDbDataSource.java:129)
	at com.alibaba.polardbx.gms.metadb.MetaDbDataSource.initXDataSourceByJdbcProps(MetaDbDataSource.java:170)
	at com.alibaba.polardbx.gms.metadb.MetaDbDataSource.initMetaDbDataSource(MetaDbDataSource.java:181)
	at com.alibaba.polardbx.gms.metadb.MetaDbDataSource.doInit(MetaDbDataSource.java:121)
	at com.alibaba.polardbx.common.model.lifecycle.AbstractLifecycle.init(AbstractLifecycle.java:43)
	at com.alibaba.polardbx.gms.metadb.MetaDbDataSource.getInstance(MetaDbDataSource.java:462)
	at com.alibaba.polardbx.server.TddlLauncher.initGms(TddlLauncher.java:229)
	at com.alibaba.polardbx.server.TddlLauncher.main(TddlLauncher.java:69)
`

**Comment by Cleverdada** [comment]
可能需要先排除第一次初始化引起的脏数据，是否可以把DN恢复到最初始的状态，然后重新用下列命令初始化看下

> 1. mysql -h127.0.0.1 -P4886 -uroot -e "alter user 'root'@'localhost' identified by 'admin'"
> 2. mysql -h127.0.0.1 -P4886 -uroot -padmin -e "create user 'root'@'%' identified by 'admin'"
> 3. mysql -h127.0.0.1 -P4886 -uroot -padmin -e "grant all on *.* to 'root'@'%'
> 4. bin/startup.sh -I -P asdf1234ghjk5678 -r "admin" -d 127.0.0.1:4886:32886 -u polardbx_root -S "123456"

**Comment by fyzjhh** [comment]
> 可能需要先排除第一次初始化引起的脏数据，是否可以把DN恢复到最初始的状态，然后重新用下列命令初始化看下
> 
> > 1. mysql -h127.0.0.1 -P4886 -uroot -e "alter user 'root'@'localhost' identified by 'admin'"
> > 2. mysql -h127.0.0.1 -P4886 -uroot -padmin -e "create user 'root'@'%' identified by 'admin'"
> > 3. mysql -h127.0.0.1 -P4886 -uroot -padmin -e "grant all on _._ to 'root'@'%'
> > 4. bin/startup.sh -I -P asdf1234ghjk5678 -r "admin" -d 127.0.0.1:4886:32886 -u polardbx_root -S "123456"


![image](https://user-images.githubusercontent.com/3634566/156730040-c1ecd86c-95d8-46fe-83c1-00241002be37.png)

从堆栈和代码上看 是初始化的时候  执行 initTsoServicesX 方法的时候 报错了。

**Comment by Cleverdada** [comment]
堆栈上看到了，initTsoServicesX 不是初始化的逻辑，是启动的逻辑
报错是说没找到leader for metadb storage, 怀疑读到了第一次初始化后的配置

**Comment by fyzjhh** [comment]
> polardbx




初始化DN和启动DN的时候 总是报的错误（图片） ， 可能与下面的错误有关

Exception in thread "main" ERR-CODE: [PXC-10004][ERR_X_PROTOCOL_RESULT] Fatal error when fetch data: Unable to switch context to user root HY000

![image](https://user-images.githubusercontent.com/3634566/156738354-26237283-17f4-4b3a-9cc4-b4fc27ab54ee.png)

**Comment by Cleverdada** [comment]
### 按照文档编译DN、CN均成功:
![image](https://user-images.githubusercontent.com/11186845/160229149-c1e42d14-1f7e-4ac9-bfc2-d139d8f9984a.png)


### 下面是测试成功的环境信息:
OS Version: CentOS Linux release 7.8.2003 (Core)
Gcc Version: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)

### 与文档中操作稍有偏差的部分如下：

#### DN:

DN指定mysqld启动后，增加了以下命令, 用于设置root密码为admin:
```
mysql -h127.0.0.1 -P4886 -uroot -e "alter user 'root'@'localhost' identified by 'admin'"
mysql -h127.0.0.1 -P4886 -uroot -padmin -e "create user 'root'@'%' identified by 'admin'"
mysql -h127.0.0.1 -P4886 -uroot -padmin -e "grant all on *.* to 'root'@'%'"

```

#### CN:
CN初始化脚本中 -r参数修改为"admin", 完整命令如下:
```
bin/startup.sh \
    -I \
    -P asdf1234ghjk5678 \
    -d 127.0.0.1:4886:32886 \
    -r "admin" \
    -u polardbx_root \
    -S "123456"
```

**Comment by Cleverdada** [comment]
> 操作路径： 源码编译DN启动后 1 初始化 执行能够正常完成 bin/startup.sh -I -P asdf1234ghjk5678 -r "admin" -d 127.0.0.1:4886:32886 -u polardbx_root -S "123456" 2 把 metaDbPasswd=BVUB3NoOBdCXPv+X2Wa3es6Ng1tzChSd9Vzdm2RVaBo= 放到 conf/server.properties 3 启动 命令没有报错 bin/startup.sh -P asdf1234ghjk5678 4 连接数据库报错了，8527端口没有监听 mysql -h127.0.0.1 -P8527 -upolardbx_root -p123456 ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)
> 
> 配置如下： ![image](https://user-images.githubusercontent.com/11186845/156718592-9b113776-ebf2-4f6c-b69a-e6e65f655c15.png)
> 
> 报错日志： ![image](https://user-images.githubusercontent.com/11186845/156718484-27920fb9-29b6-4e9d-85b0-c95171401db8.png)

这个问题确实是因为第一次初始化后有脏数据引起的，根本原因是你下面的截图中的报错: "Fatal error when fetch data: Unable to switch context to user root HY000"， 请参考上面的操作步骤重新启动

**Comment by wsm12138** [comment]
### 解决手法：
1. 清空、重置 DN 环境
```
rm -rf ${MySQL_DATADIR}
mysqld --defaults-file=/home/polardb/data/mysql/mysql4886/my4886.cnf  --initialize-insecure
mysql -h127.0.0.1 -P4886 -uroot -e "alter user 'root'@'localhost' identified by 'admin'"
mysql -h127.0.0.1 -P4886 -uroot -padmin -e "create user 'root'@'%' identified by 'admin'"
mysql -h127.0.0.1 -P4886 -uroot -padmin -e "grant all on *.* to 'root'@'%'"

or 

drop user my_polarx@127.0.0.1;
drop user my_polarx@localhost; 
drop user my_polarx; 
drop database polardbx_meta_db_polardbx;
```
#### DN 状态
![image](https://user-images.githubusercontent.com/86462784/160341804-ae683877-0a4f-452c-9eac-62a64811fa01.png)

2. CN 初始化 & 启动
```
bin/startup.sh \
    -I \
    -P asdf1234ghjk5678 \
    -d 127.0.0.1:4886:32886 \
    -r "admin" \
    -u polardbx_root \
    -S "123456"
```
PS:初始化比较久，可在数据库中 `show full processlist;` 查看正在初始化
![image](https://user-images.githubusercontent.com/86462784/160344099-d114c268-abe3-48aa-af9c-886414d63175.png)


更新生成的 metaDbPasswd 至 conf/server.properties、启动 CN
```
bin/startup.sh -P asdf1234ghjk5678
```
3. 验证 CN 启动成功
```
 mysql -h127.1 -P8527 -upolardbx_root -p123456
```
![image](https://user-images.githubusercontent.com/86462784/160344486-ca351b7b-edac-4721-8ff0-5dc111ee0f68.png)


## 操作步骤对比[官方构建说明](https://polardbx.com/quickstart/topics/quickstart-development.html)来看，之前失败原因疑似没有 `root@%` 用户，导致无法正常初始化。

**Comment by Cleverdada** [comment]
> ### 解决手法：
> 1. 清空、重置 DN 环境
> 
> ```
> rm -rf ${MySQL_DATADIR}
> mysqld --defaults-file=/home/polardb/data/mysql/mysql4886/my4886.cnf  --initialize-insecure
> mysql -h127.0.0.1 -P4886 -uroot -e "alter user 'root'@'localhost' identified by 'admin'"
> mysql -h127.0.0.1 -P4886 -uroot -padmin -e "create user 'root'@'%' identified by 'admin'"
> mysql -h127.0.0.1 -P4886 -uroot -padmin -e "grant all on *.* to 'root'@'%'"
> 
> or 
> 
> drop user my_polarx@127.0.0.1;
> drop user my_polarx@localhost; 
> drop user my_polarx; 
> drop database polardbx_meta_db_polardbx;
> ```
> 
> #### DN 状态
> ![image](https://user-images.githubusercontent.com/86462784/160341804-ae683877-0a4f-452c-9eac-62a64811fa01.png)
> 
> 2. CN 初始化 & 启动
> 
> ```
> bin/startup.sh \
>     -I \
>     -P asdf1234ghjk5678 \
>     -d 127.0.0.1:4886:32886 \
>     -r "admin" \
>     -u polardbx_root \
>     -S "123456"
> ```
> 
> PS:初始化比较久，可在数据库中 `show full processlist;` 查看正在初始化 ![image](https://user-images.githubusercontent.com/86462784/160344099-d114c268-abe3-48aa-af9c-886414d63175.png)
> 
> 更新生成的 metaDbPasswd 至 conf/server.properties、启动 CN
> 
> ```
> bin/startup.sh -P asdf1234ghjk5678
> ```
> 
> 3. 验证 CN 启动成功
> 
> ```
>  mysql -h127.1 -P8527 -upolardbx_root -p123456
> ```
> 
> ![image](https://user-images.githubusercontent.com/86462784/160344486-ca351b7b-edac-4721-8ff0-5dc111ee0f68.png)
> 
> ## 操作步骤对比[官方构建说明](https://polardbx.com/quickstart/topics/quickstart-development.html)来看，之前失败原因疑似没有 `root@%` 用户，导致无法正常初始化。

非常感谢你的补充，对社区的用户非常有帮助
