### ISSUE TITLE
Can not visit the website of document

### ISSUE THREAD

**Issue by Lloyd-Pottiger** [ApsaraDB/galaxysql#47]
https://polardbx.com/ can not visit

**Comment by hustfxj** [comment]
please try this website https://doc.polardbx.com/

**Comment by Lloyd-Pottiger** [comment]
> please try this website https://doc.polardbx.com/

this is ok, but maybe you could revise the link in first line of README?

**Comment by hustfxj** [comment]
@Lloyd-Pottiger L Thanks for your suggestion. now you also can visit https://polardbx.com/
