### ISSUE TITLE
Let the 32 databases limit configurable

### ISSUE THREAD

**Issue by datouxia** [ApsaraDB/galaxysql#48]
Try to deploy LMS product with polardbx as it database, We need to create database over 100 schools.
Then I have been told about that the limit about number of databases is 32, ant Can't adjust by config file.
Wish this limit can be configurable and please tell me why we really need this limitation?

**Comment by pyson** [comment]
Thanks your question. You can adjust the config of MAX_LOGICAL_DB_COUNT which is the limit of the  number of databases  by the following sql：
set ENABLE_SET_GLOBAL=true;
set set GLOBAL MAX_LOGICAL_DB_COUNT=xxx;

and use the following sql to check set result:
select * from metadb.inst_config where param_key='MAX_LOGICAL_DB_COUNT';

**Comment by datouxia** [comment]
Zeratulll in Wechat group just told me "Set global command result in persistented"
