### ISSUE TITLE
[Enhancement] refactor to simplify the judge bottom-join

### ISSUE THREAD

**Issue by jackwener** [ApsaraDB/galaxysql#52]
https://github.com/ApsaraDB/galaxysql/blob/aa0b41ca6db291c0561089b5c25bd4171a969194/polardbx-calcite/src/main/java/org/apache/calcite/rel/rules/JoinCommuteRule.java#L190-L200

I think we don't need to judge it's bottom-join by using `size() > 1`. 

Instead, we can just use `left() instance of Join`.

**Comment by jackwener** [comment]
How do you think? @Oldbread3

**Comment by chenzl25** [comment]
I don't think so. In VolcanoPlanner, the input of this `logicalJoin` could be a RelSubset instead of a specific Join node.

**Comment by Oldbread3** [comment]
agree with @chenzl25 , join could be hidden under any relNode(Project, Grouping, .etc), so that we need MetadataQuery to traverse whole sub-plan.

**Comment by jackwener** [comment]
I got it😀
