### ISSUE TITLE
PolarDB-X做为slave时, 会出现ERR-CODE: [PXC-4614][ERR_EXECUTE_ON_MYSQL]

### ISSUE THREAD

**Issue by methinking** [ApsaraDB/galaxysql#59]
主库mysql: 8.0.29
pxd version: 0.3.0
设置好主从同步后, 往主库批量导入数据时, PolarDB-X会出现主键冲突问题, 实际上是没有这个问题的, 主库已经写入了所有数据了, 请问这个问题是写入主库的数据太快导致的吗 ?
<img width="564" alt="WechatIMG23310" src="https://user-images.githubusercontent.com/20240078/171191582-3b557d2f-e4a6-4f95-bee0-80c371e4a1a4.png">

**Comment by hustfxj** [comment]
提供下你的表结构看看呢

**Comment by methinking** [comment]
> 提供下你的表结构看看呢。

CREATE TABLE `audio_api` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(254) DEFAULT NULL COMMENT '名称',
  `userId` int unsigned NOT NULL DEFAULT '0' COMMENT '用户Id',
  `status` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '状态|0:有效;1:无效',
  `appId` int unsigned NOT NULL DEFAULT '10001' COMMENT 'appId',
  `secretKey` varchar(64) NOT NULL DEFAULT '' COMMENT 'skey',
  `secretId` varchar(64) NOT NULL DEFAULT '' COMMENT 'sId',
  `createAt` int unsigned NOT NULL COMMENT '创建时间',
  `updateAt` int unsigned NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_user` (`userId`,`appId`,`secretKey`,`secretId`,`createAt`)
) ENGINE=InnoDB AUTO_INCREMENT=20323 DEFAULT CHARSET=utf8mb3 ROW_FORMAT=DYNAMIC

**Comment by methinking** [comment]
> 这个问题是写入主库的数据太快导致的吗 ?

我试了几次同步, 同步时好像每个表都有几率出现这个问题.

**Comment by Agilulf** [comment]
> > 这个问题是写入主库的数据太快导致的吗 ?
> 
> 我试了几次同步, 同步时好像每个表都有几率出现这个问题.

数据不敏感的话，方便提供下日志吗，目录是 polardbx-cdc镜像的 /home/admin/logs/polardbx-rpl/*

**Comment by Agilulf** [comment]
> > > > 这个问题是写入主库的数据太快导致的吗 ?
> > > 
> > > 
> > > 我试了几次同步, 同步时好像每个表都有几率出现这个问题.
> > 
> > 
> > 数据不敏感的话，方便提供下日志吗，目录是 polardbx-cdc镜像的 /home/admin/logs/polardbx-rpl/*
> 
> 可以提供的, 方便提供个邮箱吗? 我发过去

shezhiwei.szw@alibaba-inc.com

**Comment by methinking** [comment]
> > > > > 这个问题是写入主库的数据太快导致的吗 ?
> > > > 
> > > > 
> > > > 我试了几次同步, 同步时好像每个表都有几率出现这个问题.
> > > 
> > > 
> > > 数据不敏感的话，方便提供下日志吗，目录是 polardbx-cdc镜像的 /home/admin/logs/polardbx-rpl/*
> > 
> > 
> > 可以提供的, 方便提供个邮箱吗? 我发过去
> 
> [shezhiwei.szw@alibaba-inc.com](mailto:shezhiwei.szw@alibaba-inc.com)

已发送

**Comment by Agilulf** [comment]
> Referenc

是一个repo里已修复的bug，但pxd里的cdc镜像没有及时更新，很抱歉。目前最新镜像已上传，重新pxd搭建下PolarDB-X实例试试。

**Comment by methinking** [comment]
> > Referenc
> 
> 是一个repo里已修复的bug，但pxd里的cdc镜像没有及时更新，很抱歉。目前最新镜像已上传，重新pxd搭建下PolarDB-X实例试试。

明白,谢谢
