### ISSUE TITLE
AP方面的提升

### ISSUE THREAD

**Issue by ChenpiDog** [ApsaraDB/galaxysql#61]
PolarDB-X本身作为一款HTAP数据库，拥有TP和AP的能力，但主要还是TP，希望PolarDB-X能在AP领域多多发力，减少用户大数据技术的复杂度。生态方面，希望PolarDB-X能向数据湖生态靠近，例如支持Hudi外表等。

**Comment by hustfxj** [comment]
Good idea！事实上Polardb-X 提供了Native MPP的能力，我们的TP和AP是同一套SQL engine，有完备的兼容性和AP查询能力。但目前缺少列存，内部已经开说着手列存的工作了。至于你说到了支持Hudi外表的能力，暂时社区还没有资源透露。如果有兴趣，也欢迎为我们实现类似DBlink的能力。

**Comment by hustfxj** [comment]
@ChenpiDog 可以看看 https://zhuanlan.zhihu.com/p/337062566
