### ISSUE TITLE
执行json_object，结果返回字段顺序会改变，和mariadb，mysql数据库不一样

### ISSUE THREAD

**Issue by co63oc** [ApsaraDB/galaxysql#68]
mysql> SELECT JSON_OBJECT('id', 123, 'name', 'polardb-x');
+---------------------------------------------+
| JSON_OBJECT('id', 123, 'name', 'polardb-x') |
+---------------------------------------------+
| {"name":"polardb-x","id":123}               |
+---------------------------------------------+
1 row in set (0.00 sec)

mariadb数据库的结果为，这应该是和mysql数据库一样
MariaDB [(none)]> SELECT JSON_OBJECT('id', 123, 'name', 'polardb-x');
+---------------------------------------------+
| JSON_OBJECT('id', 123, 'name', 'polardb-x') |
+---------------------------------------------+
| {"id": 123, "name": "polardb-x"}            |
+---------------------------------------------+
1 row in set (0.000 sec)

**Comment by co63oc** [comment]
mysqld测试结果
mysql> SELECT JSON_OBJECT('id', 123, 'name', 'polardb-x');
+---------------------------------------------+
| JSON_OBJECT('id', 123, 'name', 'polardb-x') |
+---------------------------------------------+
| {"id": 123, "name": "polardb-x"}            |
+---------------------------------------------+
1 row in set (0.00 sec)

**Comment by F-ca7** [comment]
关于MySQL 对 json_object输出顺序的描述：https://dev.mysql.com/doc/refman/8.0/en/json.html#json-normalization
> To make lookups more efficient, MySQL also sorts the keys of a JSON object. You should be aware that the result of this ordering is subject to change and not guaranteed to be consistent across releases.

MySQL会对 JSON对象的key进行排序，但是不保证这个顺序在每个发行版都是一致的。

而PolarDB-X中调用了FastJson的接口，底层com.alibaba.fastjson.serializer.MapSerializer 是基于HashMap的遍历，这个同样也是不保证顺序的。
