### ISSUE TITLE
[suggestion] Need tags to link semantic version with commit hash

### ISSUE THREAD

**Issue by Lordess** [ApsaraDB/galaxysql#7]
It will be great, if your guy use tags. Thanks in advance.
e.g. https://github.com/microsoft/vscode/tags

**Comment by Oldbread3** [comment]
Good suggestion! Working on it.

**Comment by Oldbread3** [comment]
[v5.4.12](https://github.com/ApsaraDB/galaxysql/releases/tag/galaxysql-5.4.12) is published
