### ISSUE TITLE
CBOLogicalSemiJoinLogicalJoinTransposeRule.LASSCOM is redundant

### ISSUE THREAD

**Issue by jackwener** [ApsaraDB/galaxysql#83]
This rule is SemiJoin(LogicalJoin(X, Y), Z).

inside LogicalJoin isn't `semi/anti join`, which means that left must exist `project`.

So the patterm must be `SemiJoin-project-LogicalJoin`, this INSTANCE is redundant

**Comment by hustfxj** [comment]
I don't agree with you.  In fact  the rule only push the semiJoin for LEFT-DEEP-TREE Join Reorder , which  is  only relative to CBOLogicalSemiJoinLogicalJoinTransposeRule.INSTANCE.
```
     SJ                                LJ
    / \                               / \
  LJ    Z       ->                  SJ   Y  
 /   \                             /  \
X     Y                          X    Z

```

**Comment by hustfxj** [comment]
SemiJoin(LogicalJoin(X, Y), Z) output the types（X, Y）, and the LogicalJoin(SemiJoin(X, Y), Z) also output the same types (X, Y).

**Comment by jackwener** [comment]
I got it, it's my mistake, thanks !
